rootfs/resize: use findmnt command to detect the root device
The time when the file-system label could be detected on
/dev/disk/by-label is indetermination. So a loop must be
used to make sure the rezise service executed.

Signed-off-by: Wenbin Song <wenbin.song@nxp.com>

diff --git a/package/rootfs-resize/src/S60rootfs-resize b/package/rootfs-resize/src/S60rootfs-resize
--- a/package/rootfs-resize/src/S60rootfs-resize
+++ b/package/rootfs-resize/src/S60rootfs-resize
@@ -4,19 +4,17 @@
 #
 rootfs_resize() {
 	printf "\t Resize the rootfs: "
-	if [ -b /dev/disk/by-label/root ]
+
+	RDEV=$(findmnt -n -o SOURCE /)
+	/sbin/resize2fs ${RDEV}
+	if [ $? -eq 0 ]
 	then
-		/sbin/resize2fs /dev/disk/by-label/root
-		if [ $? -eq 0 ]
-		then
-			echo  "OK"
-		else
-			echo  "Failed"
-		fi
+		echo  "OK"
 	else
-		echo  "No find /dev/disk/by-label/root"
+		echo  "Failed"
 		exit 1
 	fi
+	echo 0
 }
 
 start() {
